### ISSUE TITLE
RFID field NOT enabled after motion outside

### ISSUE THREAD

**Issue by Kami0612** [floppyFK/kittyhack#50]
My cats don't always come in, I could see in the log file that the following steps are not always applied:

### Works:
2025-01-27 09:44:18.258 +0100 (CET) [INFO] **[PIR] OUTSIDE: Motion detected**
2025-01-27 09:44:18.322 +0100 (CET) [INFO] [BACKEND] Motion detected OUTSIDE (Block ID: 18)
2025-01-27 09:44:18.323 +0100 (CET) [INFO] [CAMERA] Resuming the TFLite processing.
2025-01-27 09:44:18.343 +0100 (CET) [INFO] **[RFID] RFID field enabled**.
2025-01-27 09:44:18.344 +0100 (CET) [INFO] [BACKEND] Started RFID reader.
2025-01-27 09:44:18.708 +0100 (CET) [INFO] [IMAGEBUFFER] Appended new element with ID 480, timestamp: 1737967458.3443563, Mouse probability: 0.0, No mouse probability: 41 to the buffer.
[...]
2025-01-27 09:44:22.297 +0100 (CET) [INFO] [RFID] Skipped 29 previous duplicate tags of 'None'
2025-01-27 09:44:22.298 +0100 (CET) [INFO] [RFID] Tag ID: '0100A2E818F34EF5' (raw Tag ID: '+ 0100A2E818F34EF5') detected at 1737967462.297646 (read cycle 45195/∞)
2025-01-27 09:44:22.347 +0100 (CET) [INFO] [IMAGEBUFFER] Appended new element with ID 488, timestamp: 1737967462.015712, Mouse probability: 0.0, No mouse probability: 85 to the buffer.
2025-01-27 09:44:22.354 +0100 (CET) [INFO] [BACKEND] RFID tag detected: '0100A2E818F34EF5'.
2025-01-27 09:44:22.355 +0100 (CET) [INFO] [RFID] RFID field disabled.
2025-01-27 09:44:22.356 +0100 (CET) [INFO] [BACKEND] Detected RFID tag 0100A2E818F34EF5 matches a known tag. Stop RFID reader.
2025-01-27 09:44:22.357 +0100 (CET) [INFO] [BACKEND] Detected RFID tag is in the database. Kitty is allowed to enter...

### Doesn`t works:
2025-01-27 11:11:23.890 +0100 (CET) [INFO] [PIR] OUTSIDE: **Motion detected**
2025-01-27 11:11:24.490 +0100 (CET) [INFO] [IMAGEBUFFER] Appended new element with ID 96, timestamp: 1737972684.1556835, Mouse probability: 0.0, No mouse probability: 50 to the buffer.
[...]
2025-01-27 11:11:34.020 +0100 (CET) [INFO] [PIR] OUTSIDE: No motion

Shouldn't these steps have to be carried out every time there is movement outside if the PIR switch-on delay has been exceeded?
Is it possible that a switch-on delay is still running and prevents the RFID reader from being activated again?
Actually, the reader should be activated with every movement.

[kittyhack.log](https://github.com/user-attachments/files/18557168/kittyhack.log)

**Comment by floppyFK** [comment]
###  Thanks for the logs! OK, let's analyze it:

In line 22262 was a mouse detected:
```
2025-01-27 11:10:21.184 +0100 (CET) [INFO] [IMAGEBUFFER] Appended new element with ID 1, timestamp: 1737972620.84988, Mouse probability: 89, No mouse probability: 0.0 to the buffer.
```
Well, probably a false-positive? But since the measured value exeeded your configured threshold (81) and you have the prey detection enabled, the inside stays locked (I have not yet invested much time in the prey detection stuff... there is still a lot to do).
Probably not very clear here in the logs. I will add here more log outputs for such conditions.
But this was the previous motion block... as there was a part with no motion inbetween, it should have no impact on the next motion block at 11:11:23, that you mentioned.


The RFID field itself was still active from that previous motion event, since the delay of the previous motion event and the actual motion event was just 14.030 seconds long.
> **Short declaration:** There is a delay of 15.000 seconds for the deactivation of the RFID field after the motion stops when no RFID was detected (bug - more below). Just to prevent too much toggling of the field power if you have a ultra sneaky cat or moving objects which triggers the outside PIR.


Here the direct re-activation of the RFID Field at 11:10:28 (as already said, shouldn't be like this, more explanation below). It stays then active all the time until 11:12:10:
```
2025-01-27 11:10:28.576 +0100 (CET) [INFO] [RFID] Tag ID: '0100A2E818F34EAD' (raw Tag ID: '+ 0100A2E818F34EAD') detected at 1737972628.576672 (read cycle 536/∞)
2025-01-27 11:10:28.596 +0100 (CET) [INFO] [BACKEND] RFID tag detected: '0100A2E818F34EAD'.
2025-01-27 11:10:28.598 +0100 (CET) [INFO] [RFID] RFID field disabled.
2025-01-27 11:10:28.599 +0100 (CET) [INFO] [BACKEND] Detected RFID tag 0100A2E818F34EAD matches a known tag. Stop RFID reader.
...
2025-01-27 11:10:28.703 +0100 (CET) [INFO] [RFID] RFID field enabled.
...
2025-01-27 11:12:10.655 +0100 (CET) [INFO] [RFID] RFID field disabled.
```


The invalidation of `tag_id_valid` conclusion happened when the previous motion outside stopped at 11:11:03, as well as the invalidation of the tag_id itself directly afterwards:
```
2025-01-27 11:11:03.047 +0100 (CET) [INFO] [BACKEND] Motion stopped OUTSIDE (Block ID: '2')
...
2025-01-27 11:11:03.050 +0100 (CET) [INFO] [BACKEND] Tag timeout reached. Forget the tag.
```
So this means, after 11:11:03 we need to actively read a new tag, which seemingly did not happen, although the RFID field was active.

-------------

#### Regarding the field power bug:
I see, there is also a RFID "Off-On" cycle after a valid RFID was detected, which should not happen. I will change the logic in the next version.
To prevent a flooding of the logfile, the log entry for a detected tag will just be shown once when the `tag_id_valid` flag is False and the detected tag matches the according criteria (either a match of the read RFID and the Database, any RFID, ... depending on the configuration of the entrance mode).
But you can increase the loglevel from `INFO` to `DEBUG` in the configuration panel. Then you will see every new detected RFID from the Tectus Chip, even if it is identical with the previously detected RFID.
You should see then log messages like this:
```
[RFID] Skipping duplicate tag: 'TAG-ID-OF-THE-CAT'
```

Unfortunately you will also receive every read cycle timeout of the RFID reader every 1000ms.
If you dont want these messages you could just delete the line __165__ `logging.debug(f"[RFID] Cycle {cycle+1}/{read_cycles if read_cycles != 0 else '∞'} | RFID run state: {self.get_run_state()}")` in the file `/root/kittyhack/src/rfid.py`:
##### rfid.py:
```python
[164]                    while (read_cycles == 0 or cycle < read_cycles) and (self.get_run_state() != RfidRunState.stop_requested):
[165]                        logging.debug(f"[RFID] Cycle {cycle+1}/{read_cycles if read_cycles != 0 else '∞'} | RFID run state: {self.get_run_state()}")
[166]                        ready, _, _ = select.select([f], [], [], 1.0)
```
And restart your kittyflap after the change.

---------------

### OK, conclusion:
The RFID field and power was active, so your cat *should* have been detected.
Either her RFID chip was not near enough or there is still an issue in such motion on-off-on situations. I will do some tests.

---------------


ToDo's for @floppyFK : 
- Add more log outputs for all decisions of the unlocking logic
- Analyze and check the RFID read process

ToDo for @Kami0612 :
- Set the loglevel to `DEBUG`

**Comment by KDBhimself** [comment]
I had something similar last night. Normally, it detects Nina immediately, even from meters away. I deleted her, restarted, and added her back. It works fine now. 

![Image](https://github.com/user-attachments/assets/89d0c199-9a59-4954-a43c-bdb38a8f3246)

**Comment by FabulousGee** [comment]
@floppyFK  got the same issue with v1.2.8 - no RFID found. Restart did not work, still no RFID found. Current configuration is "All cats" if it matters for RFID-field activation.

**Comment by floppyFK** [comment]
Hmm, did you reboot after updating to v1.2.8? That’s very strange.
The mode for the entrance shouldn't have any impact as the reader should continue until a valid tag was detected.

I’ve just released v1.2.9, which includes additional log output for the decision-making process of the unlocking procedure. You could try again with this version.

Does the issue occur on both of your kittyflaps (assuming the 16GB version is running again)?

**Comment by FabulousGee** [comment]
Still won't work for me with v1.2.9. FYI, "All cats with RFID" was active this time. Have no cats registered currently.
I let her in with manual override. Her head/neck was right at the door for the period of first outside motion and manual override. So the RFID should've been detected properly.
I stopped the "logging.info(f"[RFID] Skipping line: '{line}'")" from spamming my log, so don't mind that.

As for the 16GB variant I will test and get a log as soon as I recover it with the new image.

[kittyhack.log](https://github.com/user-attachments/files/18595082/kittyhack.log)

**Comment by floppyFK** [comment]
But you received a log entry "`Skipping line: xxx`" (probably `None` for the xxx part) once ever second (and not faster), while this line was active?

**Comment by FabulousGee** [comment]
Would even say faster than that :-)

```
2025-01-29 23:14:16.663 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.669 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.670 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.670 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.670 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.671 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.671 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.671 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.672 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.672 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.672 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.673 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.673 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.673 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.674 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.674 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.675 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.675 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.676 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.676 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.676 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.677 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.677 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.677 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.677 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.678 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.678 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.678 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.679 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.679 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.679 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.680 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.680 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.680 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.681 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.681 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.682 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.682 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.682 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.683 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.683 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.683 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.684 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.684 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.684 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.685 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.685 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.685 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.685 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.686 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.686 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.686 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.687 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.687 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.687 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.688 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.688 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.689 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.689 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.689 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.690 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.690 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.690 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.691 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.691 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.691 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.692 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.692 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.693 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.693 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.693 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.693 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.694 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.694 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.694 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.695 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.695 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.695 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.696 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.696 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.697 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.697 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.697 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.698 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.698 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.698 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.699 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.699 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.699 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.700 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.700 +0100 (CET) [INFO] [RFID] Skipping line: ''
2025-01-29 23:14:16.700 +0100 (CET) [INFO] [RFID] Skipping line: ''
```

**Comment by floppyFK** [comment]
This means that there is either no serial device present or the tectus is flooding the you permanently with newlines (normally it should only send new data to the serial interface if it reads something. If the Python script receives nothing within 1000ms, it restarts the read process and log an empty message) 

What is the output of: 
```bash
ls -l /dev/serial0
stat /dev/serial0
```
?

**Comment by FabulousGee** [comment]
```
root@kittyflap:~# ls -l /dev/serial0
lrwxrwxrwx 1 root root 5 29. Jan 22:20 /dev/serial0 -> ttyS0

root@kittyflap:~# stat /dev/serial0
 Datei: /dev/serial0 -> ttyS0
 Größe: 5               Blöcke: 0          EA Block: 4096   symbolische Verknüpfung
Gerät: 0/5      Inode: 510         Verknüpfungen: 1
Zugriff: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Zugriff: 2025-01-29 22:20:08.955999999 +0000
Modifiziert: 2025-01-29 22:20:08.919999999 +0000
Geändert: 2025-01-29 22:20:08.919999999 +0000
Geburt: 2025-01-29 22:20:08.919999999 +0000
```

**Comment by FabulousGee** [comment]
Can confirm everything is working fine with the 16GB image you provided... So I guess this is either hardware-related or a local software issue regarding versions or anything.

I will swap the kittyflaps tomorrow and try reinstalling my 32GB asap - so we can see if it was caused by a hardware failure or software issue.

**Comment by Kami0612** [comment]
No Problems with 16gb.

**Comment by KDBhimself** [comment]
The cat can only enter if it is set to "all cats", then the Kittyflap detects her without any problem, even from meters away. With the Kittflap on "only registered cats" she cannot enter.

![Image](https://github.com/user-attachments/assets/df3addd4-f18d-4e5d-b385-369dba9b660d)
